apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stash-box.fullname" . }}-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi