apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "stash-box.fullname" . }}
  labels:
    {{- include "stash-box.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stash-box.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stash-box.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stash-box.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.box.repository }}:{{ .Values.image.box.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.box.pullPolicy }}
          {{ include "stash-box.environment" . | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "stash-box.fullname" . }}-data
              mountPath: /root/.stash-box
              {{- if not .Values.persistence.enabled}}
              emptyDir: {}
              {{- end }}
      {{- if .Values.configuration.enabled}}
      initContainers:
        {{- if .Values.configuration.enabled }}
        - name: {{ .Values.configuration.initContainer.name }}
          image: {{ .Values.configuration.initContainer.image }}
          {{- if .Values.configuration.initContainer.securityContext }}
          securityContext:
            {{- toYaml .Values.configuration.initContainer.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.configuration.initContainer.command }}
          command: {{ toYaml .Values.configuration.initContainer.command | nindent 12 }}
          {{- end }}
          {{- if .Values.configuration.initContainer.args }}
          args: {{ toYaml .Values.configuration.initContainer.args | nindent 12 }}
          {{- end }}
          {{ include "stash-box.environment" . | nindent 10 }}
          volumeMounts:
            - name: {{ include "stash-box.fullname" . }}-data
              mountPath: /root/.stash-box
              {{- if not .Values.persistence.enabled}}
              emptyDir: {}
              {{- end }}
            {{- range .Values.configuration.initContainer.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{ end }}
            {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.configuration.enabled }}
        - name: init
          configMap:
            name: init
        - name: templates
          configMap:
            name: templates
        {{- end }}
  {{- if .Values.persistence.enabled}}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "stash-box.fullname" . }}-data
      spec:
        accessModes:
          - {{ .Values.persistence.volumes.config.accessMode }}
        {{- with .Values.persistence.volumes.config.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.volumes.config.size }}
  {{- end }}