apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stash.fullname" . }}-environment-variables
data:
  STASH_STASH: {{ .Values.config.directories.data | quote }}
  STASH_GENERATED: {{ .Values.config.directories.generated | quote }}
  STASH_METADATA: {{ .Values.config.directories.metadata | quote }}
  STASH_CACHE: {{ .Values.config.directories.cache | quote }}
  STASH_PORT: "{{ .Values.service.port }}"
  SPECIAL_LEVEL: {{ .Values.config.special.level | quote }}
  SPECIAL_TYPE: {{ .Values.config.special.type | quote }}