{{- if .Values.configuration.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: templates
  namespace: {{ .Release.Namespace }}
data:
  stash-box-config.yml: |
    {{- tpl .Values.configuration.templateConfig . | nindent 4 }}
{{- end -}}